name: gcs deploy

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  upload_file_gcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ./
          destination: neriyu-content
