name: gcs deploy

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  upload_file_gcs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ./build
          destination: neriyu-content
